repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: cnvanalysis
  description: Nextflow pipeline to generate CNV analysis from pod5 files
  author: msagniez
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
