contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #cnvanalysis channel"
    url: https://nfcore.slack.com/channels/cnvanalysis
    about: Discussion about the nf-core/cnvanalysis pipeline
